image: docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME_$CI_PIPELINE_ID .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME_$CI_PIPELINE_ID
  only:
    - prn-prod
    - prn-dev
  tags:
    - cluster
    - kubernetes

development_deploy:
  image: reg.jagajam.com/ops/images:kube
  variables:
    DOMAIN: prn.c-cube.ru
    NODE_ENV: production
  stage: deploy
  script:
    - envsubst < nweb.yml | kubectl --kubeconfig=$KUBE_CONFIG apply -f -
    - kubectl --kubeconfig=$KUBE_CONFIG patch ing nweb-${CI_COMMIT_REF_SLUG} --type merge --patch "$(cat auth-patch.yml)"
  only:
    - prn-dev
  tags:
    - cluster
    - kubernetes

production_deploy:
  image: reg.jagajam.com/ops/images:kube
  variables:
    DOMAIN: prn.c-cube.ru
    NODE_ENV: production
  stage: deploy
  script:
    - envsubst < nweb.yml | kubectl --kubeconfig=$KUBE_CONFIG apply -f -
  only:
    - prn-prod
  tags:
    - cluster
    - kubernetes
