---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nweb-${CI_COMMIT_REF_SLUG}
  name: nweb-${CI_COMMIT_REF_SLUG}
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nweb-${CI_COMMIT_REF_SLUG}
  template:
    metadata:
      labels:
        app: nweb-${CI_COMMIT_REF_SLUG}
      name: nweb-${CI_COMMIT_REF_SLUG}
    spec:
      containers:
        - image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME_$CI_PIPELINE_ID
          name: nweb-${CI_COMMIT_REF_SLUG}
          env:
            - name: NODE_ENV
              value: ${NODE_ENV}
          readinessProbe:
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 2
            failureThreshold: 2
            httpGet:
              path: /
              port: 3000
              httpHeaders:
                - name: Accept
                  value: application/json
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              httpHeaders:
                - name: Accept
                  value: application/json
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nweb-${CI_COMMIT_REF_SLUG}
  name: nweb-${CI_COMMIT_REF_SLUG}
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nweb-${CI_COMMIT_REF_SLUG}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: nweb-${CI_COMMIT_REF_SLUG}
  name: nweb-${CI_COMMIT_REF_SLUG}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - ${DOMAIN}
  rules:
    - host: ${DOMAIN}
      http:
        paths:
          - backend:
              serviceName: nweb-${CI_COMMIT_REF_SLUG}
              servicePort: 80
            path: /
