
const icons = {

  // Logotypes

  logo_analytics: require('./img/logo_analytics.svg'),
  logo_content: require('./img/logo_content.svg'),
  logo_dashboard: require('./img/logo_dashboard.svg'),
  logo_index: require('./img/logo_index.svg'),
  logo_influence: require('./img/logo_influence.svg'),
  logo_text: require('./img/logo_text.svg'),
  logo_messenger: require('./img/logo_messenger.svg'),
  logo_rating: require('./img/logo_rating.svg'),
  logo_sign: require('./img/logo_sign.svg'),
  logo_statistics: require('./img/logo_statistics.svg'),
  logo_suite: require('./img/logo_suite.svg'),

  // Social Networks

  ch: require('./img/ch.svg'),
  ch_colored: require('./img/ch_colored.svg'),
  fb: require('./img/__fb.svg'),
  fb_bg: require('./img/fb_bg.svg'),
  fb_colored: require('./img/__fb_colored.svg'),
  ig: require('./img/__ig.svg'),
  ig_bg: require('./img/ig_bg.svg'),
  ig_colored: require('./img/__ig_colored.svg'),
  mx: require('./img/mx.svg'),
  mx_bg: require('./img/mx_bg.svg'),
  mx_colored: require('./img/mx_colored.svg'),
  inst: require('./img/__ig.svg'),
  inst_bg: require('./img/ig_bg.svg'),
  inst_colored: require('./img/__ig_colored.svg'),
  li: require('./img/li.svg'),
  li_colored: require('./img/li_colored.svg'),
  ok: require('./img/ok.svg'),
  ok_bg: require('./img/ok_bg.svg'),
  ok_colored: require('./img/ok_colored.svg'),
  rt: require('./img/rt.svg'),
  rt_colored: require('./img/rt_colored.svg'),
  tc: require('./img/tc.svg'),
  tc_colored: require('./img/tc_colored.svg'),
  tg: require('./img/tg.svg'),
  tg_bg: require('./img/tg_bg.svg'),
  tg_colored: require('./img/tg_colored.svg'),
  tt: require('./img/tt.svg'),
  tt_bg: require('./img/tt_bg.svg'),
  tt_colored: require('./img/tt_colored.svg'),
  tw: require('./img/tw.svg'),
  tw_bg: require('./img/tw_bg.svg'),
  tw_colored: require('./img/tw_colored.svg'),
  vb: require('./img/vb.svg'),
  vb_colored: require('./img/vb_colored.svg'),
  vc: require('./img/vc.svg'),
  vc_colored: require('./img/vc_colored.svg'),
  vk: require('./img/vk.svg'),
  vk_bg: require('./img/vk_bg.svg'),
  vk_colored: require('./img/vk_colored.svg'),
  yt: require('./img/yt.svg'),
  yt_bg: require('./img/yt_bg.svg'),
  yt_colored: require('./img/yt_colored.svg'),
  yz: require('./img/yz.svg'),
  yz_bg: require('./img/yz_bg.svg'),
  yz_colored: require('./img/yz_colored.svg'),

  // Grades

  grade_a_plus: require('./img/grade_a+.svg'),
  grade_a: require('./img/grade_a.svg'),
  grade_b: require('./img/grade_b.svg'),
  grade_c: require('./img/grade_c.svg'),
  grade_d: require('./img/grade_d.svg'),
  grade_a_plus_colored: require('./img/grade_a+_colored.svg'),
  grade_a_colored: require('./img/grade_a_colored.svg'),
  grade_b_colored: require('./img/grade_b_colored.svg'),
  grade_c_colored: require('./img/grade_c_colored.svg'),
  grade_d_colored: require('./img/grade_d_colored.svg'),

  // Industry

  industry_auto_moto: require('./img/industry_auto_moto.svg'),
  industry_beauty: require('./img/industry_beauty.svg'),
  industry_electronics: require('./img/industry_electronics.svg'),
  industry_fashion: require('./img/industry_fashion.svg'),
  industry_finance: require('./img/industry_finance.svg'),
  industry_food_retail: require('./img/industry_food_retail.svg'),
  industry_media: require('./img/industry_media.svg'),
  industry_retail: require('./img/industry_retail.svg'),

  // Languages

  lang_de: require('./img/lang_de.svg'),
  lang_en: require('./img/lang_en.svg'),
  lang_ru: require('./img/lang_ru.svg'),

  // Payment Systems

  mastercard: require('./img/mastercard.svg'),
  mastercard_bw: require('./img/mastercard_bw.svg'),
  mir: require('./img/mir.svg'),
  mir_bw: require('./img/mir_bw.svg'),
  qiwi_bw: require('./img/qiwi_bw.svg'),
  visa: require('./img/visa.svg'),
  visa_bw: require('./img/visa_bw.svg'),
  webmoney_bw: require('./img/webmoney_bw.svg'),
  yandex_money_bw: require('./img/yandex_money_bw.svg'),

  // Tech Icons

  admin: require('./img/admin.svg'),
  advertising: require('./img/advertising.svg'),
  analyzing: require('./img/analyzing.svg'),
  arrow_down: require('./img/arrow_down.svg'),
  arrow_down_filled: require('./img/arrow_down_filled.svg'),
  arrow_left: require('./img/arrow_left.svg'),
  arrow_right: require('./img/arrow_right.svg'),
  arrow_up: require('./img/arrow_up.svg'),
  arrow_up_filled: require('./img/arrow_up_filled.svg'),
  attention: require('./img/attention.svg'),
  blocked: require('./img/blocked.svg'),
  bookmarks_selected: require('./img/bookmarks_selected.svg'),
  bookmarks_unselected: require('./img/bookmarks_unselected.svg'),
  calendar: require('./img/calendar.svg'),
  calendar_1_date: require('./img/calendar_1_date.svg'),
  calendar_2_date: require('./img/calendar_2_date.svg'),
  calendar_past_date: require('./img/calendar_past_date.svg'),
  calendar_present_date: require('./img/calendar_present_date.svg'),
  case: require('./img/case.svg'),
  check: require('./img/check.svg'),
  check_circle: require('./img/check_circle.svg'),
  choice_ok_no: require('./img/choice_ok_no.svg'),
  choice_plus_minus: require('./img/choice_plus_minus.svg'),
  circle: require('./img/circle.svg'),
  clock: require('./img/clock.svg'),
  color_picker: require('./img/color_picker.svg'),
  comment: require('./img/comment.svg'),
  comment_filled: require('./img/comment_filled.svg'),
  compare: require('./img/compare.svg'),
  complete: require('./img/complete.svg'),
  connected: require('./img/connected.svg'),
  credit_card: require('./img/credit_card.svg'),
  cross: require('./img/cross.svg'),
  cross_circle: require('./img/cross_circle.svg'),
  date_past: require('./img/date_past.svg'),
  date_present: require('./img/date_present.svg'),
  delete: require('./img/delete.svg'),
  dev: require('./img/dev.svg'),
  disconnect: require('./img/disconnect.svg'),
  download: require('./img/download.svg'),
  edit: require('./img/edit.svg'),
  error: require('./img/error.svg'),
  file: require('./img/file.svg'),
  filetype_pdf: require('./img/filetype_pdf.svg'),
  filetype_ppt: require('./img/filetype_ppt.svg'),
  filetype_xls: require('./img/filetype_xls.svg'),
  filters: require('./img/filters.svg'),
  globe: require('./img/globe.svg'),
  gmt: require('./img/gmt.svg'),
  graph: require('./img/graph.svg'),
  graph_bars: require('./img/graph_bars.svg'),
  graph_line: require('./img/graph_line.svg'),
  graph_pie: require('./img/graph_pie.svg'),
  group: require('./img/group.svg'),
  help: require('./img/help.svg'),
  image: require('./img/image.svg'),
  item_add: require('./img/item_add.svg'),
  item_duplicate: require('./img/item_duplicate.svg'),
  item_edit: require('./img/item_edit.svg'),
  item_remove: require('./img/item_remove.svg'),
  like: require('./img/like.svg'),
  like_filled: require('./img/like_filled.svg'),
  loader: require('./img/loader.svg'),
  loading_circle: require('./img/loading_circle.svg'),
  loading_dots: require('./img/loading_dots.svg'),
  loading_dots_square: require('./img/loading_dots_square.svg'),
  locked: require('./img/locked.svg'),
  logout: require('./img/logout.svg'),
  mean: require('./img/mean.svg'),
  minus: require('./img/minus.svg'),
  minus_circle: require('./img/minus_circle.svg'),
  more: require('./img/more.svg'),
  move_tool: require('./img/move_tool.svg'),
  no_data: require('./img/no_data.svg'),
  no_picture: require('./img/no_picture.svg'),
  none: require('./img/none.svg'),
  notification: require('./img/notification.svg'),
  notification_active: require('./img/notification_active.svg'),
  organic: require('./img/organic.svg'),
  plus: require('./img/plus.svg'),
  plus_circle: require('./img/plus_circle.svg'),
  precent: require('./img/precent.svg'),
  refresh: require('./img/refresh.svg'),
  rename: require('./img/rename.svg'),
  report: require('./img/report.svg'),
  repost: require('./img/repost.svg'),
  repost_filled: require('./img/repost_filled.svg'),
  rouble: require('./img/rouble.svg'),
  sand_clock: require('./img/sand_clock.svg'),
  save: require('./img/save.svg'),
  saved: require('./img/saved.svg'),
  search: require('./img/search.svg'),
  send: require('./img/send.svg'),
  settings: require('./img/settings.svg'),
  share_in: require('./img/share_in.svg'),
  share_out: require('./img/share_out.svg'),
  sherif: require('./img/sherif.svg'),
  sigma: require('./img/sigma.svg'),
  smile: require('./img/smile.svg'),
  smile_neutral: require('./img/smile_neutral.svg'),
  smile_sad: require('./img/smile_sad.svg'),
  start: require('./img/start.svg'),
  stats_down: require('./img/stats_down.svg'),
  stats_up: require('./img/stats_up.svg'),
  stop: require('./img/stop.svg'),
  table_sort_down: require('./img/table_sort_down.svg'),
  table_sort_up: require('./img/table_sort_up.svg'),
  tag: require('./img/tag.svg'),
  user: require('./img/user.svg'),
  view_grid: require('./img/view_grid.svg'),
  view_list: require('./img/view_list.svg'),
  warning: require('./img/warning.svg'),

  // Countries

  country_armenia: require('./img/country_armenia.svg'),
  country_azerbaijan: require('./img/country_azerbaijan.svg'),
  country_belarus: require('./img/country_belarus.svg'),
  country_kazakhstan: require('./img/country_kazakhstan.svg'),
  country_kyrgyzstan: require('./img/country_kyrgyzstan.svg'),
  country_moldova: require('./img/country_moldova.svg'),
  country_russia: require('./img/country_russia.svg'),
  country_tajikistan: require('./img/country_tajikistan.svg'),
  country_turkmenistan: require('./img/country_turkmenistan.svg'),
  country_ukraine: require('./img/country_ukraine.svg'),
  country_uzbekistan: require('./img/country_uzbekistan.svg'),
}

export type IIcon = keyof typeof icons

export default icons
